# Generated by Django 3.1.1 on 2020-11-12 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_squashed_0018_keywords_keyword_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternPub',
            fields=[
                ('pub_id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Pattern Publishers',
            },
        ),
        migrations.AddField(
            model_name='items',
            name='item_img_patternback',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='item_is_pattern',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='item_is_yardage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='item_pattern_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='item_pattern_size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='item_yardage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='item_pattern_pub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='inv.patternpub'),
        ),
    ]
